[custom]
; ===================== 基础规则 =====================
ruleset=🎯 Mainland,https://clashrules.chenzisu.workers.dev/LocalAreaNetwork.list
ruleset=🎯 Mainland,https://clashrules.chenzisu.workers.dev/UnBan.list

; ===================== 广告过滤 =====================
ruleset=🛑 Advertising,https://clashrules.chenzisu.workers.dev/BanAD.list
ruleset=🛑 Advertising,https://clashrules.chenzisu.workers.dev/BanProgramAD.list
ruleset=🛑 Advertising,https://clashrules.chenzisu.workers.dev/BanEasyList.list
ruleset=🛑 Advertising,https://clashrules.chenzisu.workers.dev/BanEasyListChina.list
ruleset=🍃 BanProgramAD,https://clashrules.chenzisu.workers.dev/BanProgramAD.list

; ===================== 国内增强 =====================
ruleset=🎯 Mainland,https://clashrules.chenzisu.workers.dev/ChinaMedia.list

; ===================== AI 工具(独立分流)=====================
; ruleset=💬 Intelligence,https://clashrules.chenzisu.workers.dev/OpenAi.list
; ruleset=💬 Intelligence,https://clashrules.chenzisu.workers.dev/Gemini.list
; ruleset=💬 Intelligence,https://clashrules.chenzisu.workers.dev/Anthropic.list
; ruleset=💬 Intelligence,https://clashrules.chenzisu.workers.dev/Claude.list
ruleset=💬 Intelligence,https://clashrules.chenzisu.workers.dev/AI.list
ruleset=💬 Intelligence,https://clashrules.chenzisu.workers.dev/AppleIntelligence.list

; ===================== 购物/支付 =====================
ruleset=💰 PayPal,https://clashrules.chenzisu.workers.dev/PayPal.list
ruleset=🛍️ Amazon,https://clashrules.chenzisu.workers.dev/Amazon.list

; ===================== 流媒体 =====================
ruleset=📺 YouTube,https://clashrules.chenzisu.workers.dev/YouTube.list
ruleset=📺 DisneyPlus,https://clashrules.chenzisu.workers.dev/DisneyPlus.list
ruleset=📺 Netflix,https://clashrules.chenzisu.workers.dev/Netflix.list

; ===================== Apple  =====================
ruleset=🍎 Apple,https://clashrules.chenzisu.workers.dev/AppleFitness.list
ruleset=🍎 Apple,https://clashrules.chenzisu.workers.dev/MyAppleTV.list
ruleset=🍎 Apple,https://clashrules.chenzisu.workers.dev/AppleTV.list
ruleset=🍎 Apple,https://clashrules.chenzisu.workers.dev/Apple.list

; ===================== Google =====================
ruleset=🌍 Google,https://clashrules.chenzisu.workers.dev/GoogleOneVPN.list
ruleset=🌍 Google,https://clashrules.chenzisu.workers.dev/GoogleFCM.list
ruleset=🌍 Google,https://clashrules.chenzisu.workers.dev/Google.list

; ===================== Game =====================
ruleset=🎮 PokemonTCG,https://clashrules.chenzisu.workers.dev/PokemonTCG.list
ruleset=🎮 Game,https://clashrules.chenzisu.workers.dev/PokemonGO.list
ruleset=🎮 Game,https://clashrules.chenzisu.workers.dev/Nintendo.list
ruleset=🎮 Game,https://clashrules.chenzisu.workers.dev/Sony.list
ruleset=🎮 Game,https://clashrules.chenzisu.workers.dev/PlayStation.list
ruleset=🎮 Game,https://clashrules.chenzisu.workers.dev/Steam.list

; ===================== 大陆网站 =====================
ruleset=🎯 Mainland,https://clashrules.chenzisu.workers.dev/ChinaDomain.list
ruleset=🎯 Mainland,https://clashrules.chenzisu.workers.dev/ChinaCompanyIp.list

; ===================== GFW 增强 =====================
ruleset=🚀 Global,https://clashrules.chenzisu.workers.dev/Telegram.list
ruleset=🚀 Global,https://clashrules.chenzisu.workers.dev/Instagram.list
ruleset=🚀 Global,https://clashrules.chenzisu.workers.dev/WhatsApp.list
ruleset=🚀 Global,https://clashrules.chenzisu.workers.dev/Reddit.list
ruleset=🚀 Global,https://clashrules.chenzisu.workers.dev/LinkedIn.list
ruleset=🚀 Global,https://clashrules.chenzisu.workers.dev/Github.list
ruleset=🚀 Global,https://clashrules.chenzisu.workers.dev/Mikan.list
ruleset=🚀 Global,https://clashrules.chenzisu.workers.dev/Hitun.list

ruleset=🚀 Global,https://clashrules.chenzisu.workers.dev/ProxyGFWlist.list

; ===================== 地区规则 =====================
ruleset=🎯 Mainland,[]GEOIP,CN

; ===================== final =====================
ruleset=🐟 Final,[]FINAL


; ============================================================
;                    代理策略分组
; ============================================================
; 主策略
; custom_proxy_group=🚀 Global`select`[]🇭🇰 Auto-HK`[]🇨🇳 Auto-TW`[]🇺🇲 Auto-US`[]🇯🇵 Auto-JP`[]🇸🇬 Auto-SG`[]📲 GoogleVPN`[]DIRECT
custom_proxy_group=🚀 Global`select`[]🇭🇰 Auto-HK`[]🇨🇳 Auto-TW`[]🇺🇲 Auto-US`[]🇯🇵 Auto-JP`[]🇸🇬 Auto-SG

; 服务分流策略
; custom_proxy_group=💬 Intelligence`select`[]🇸🇬 Auto-SG`[]🇺🇲 Auto-US`[]📲 GoogleVPN
custom_proxy_group=💬 Intelligence`select`[]🇸🇬 Auto-SG`[]🇯🇵 Auto-JP`[]🇨🇳 Auto-TW`[]🇺🇲 Auto-US
custom_proxy_group=🍎 Apple`select`[]💬 Intelligence`[]🇭🇰 Auto-HK`[]🇨🇳 Auto-TW`[]🇺🇲 Auto-US`[]🇯🇵 Auto-JP`[]🇸🇬 Auto-SG`[]DIRECT
custom_proxy_group=🌍 Google`select`[]🇭🇰 Auto-HK`[]🇨🇳 Auto-TW`[]🇺🇲 Auto-US`[]🇯🇵 Auto-JP`[]🇸🇬 Auto-SG
custom_proxy_group=🎮 Game`select`(Game|游戏|IPLC)`[]🚀 Global`[]DIRECT
custom_proxy_group=🎮 PokemonTCG`select`[]🎮 Game`[]DIRECT
; custom_proxy_group=💰 PayPal`select`[]🇺🇲 Auto-US`[]📲 GoogleVPN`[]DIRECT
custom_proxy_group=💰 PayPal`select`[]🇺🇲 Auto-US`[]DIRECT
custom_proxy_group=🛍️ Amazon`select`[]🇺🇲 Auto-US`[]🇯🇵 Auto-JP`[]DIRECT
custom_proxy_group=📺 YouTube`select`[]📺 YouTube-Smart`[]🚀 Global
custom_proxy_group=📺 Netflix`select`[]📺 Netflix-Smart`[]🚀 Global
custom_proxy_group=📺 DisneyPlus`select`[]📺 DisneyPlus-Smart`[]🚀 Global

custom_proxy_group=🎯 Mainland`select`[]DIRECT`[]🚀 Global
custom_proxy_group=🛑 Advertising`select`[]REJECT`[]DIRECT
custom_proxy_group=🍃 BanProgramAD`select`[]REJECT`[]DIRECT
custom_proxy_group=🐟 Final`select`[]🚀 Global`[]DIRECT

; ============================================================
;                 Auto Region Pools (url-test)
; ============================================================
custom_proxy_group=🇭🇰 Auto-HK`url-test`^(?!.*(Game|游戏|IPLC)).*(港|HK|hk|Hong Kong|HongKong|hongkong).*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇺🇲 Auto-US`url-test`^(?!.*(Game|游戏|IPLC)).*(美国|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States).*`http://www.gstatic.com/generate_204`300,,150
custom_proxy_group=🇨🇳 Auto-TW`url-test`^(?!.*(Game|游戏|IPLC)).*(台|新北|彰化|TW|Taiwan).*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇯🇵 Auto-JP`url-test`^(?!.*(Game|游戏|IPLC)).*(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan).*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇸🇬 Auto-SG`url-test`^(?!.*(Game|游戏|IPLC)).*(新加坡|坡|狮城|SG|Singapore).*`http://www.gstatic.com/generate_204`300,,50
; custom_proxy_group=📲 GoogleVPN`url-test`(GoogleVPN|PixelVPN)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=📺 YouTube-Smart`url-test`^(?!.*(Game|游戏|IPLC)).*(港|HK|Hong Kong).*`https://www.youtube.com/premium`1800,,400
custom_proxy_group=📺 Netflix-Smart`url-test`^(?!.*(Game|游戏|IPLC)).*(港|HK|Hong Kong).*`https://www.netflix.com/title/70143836`1800,,500
custom_proxy_group=📺 DisneyPlus-Smart`url-test`^(?!.*(Game|游戏|IPLC)).*(台|TW|Taiwan).*`https://www.disneyplus.com/`1800,,500

; ============================================================
;                 Rule Generator 配置
; ============================================================
enable_rule_generator=true
overwrite_original_rules=true
clash_rule_base=https://clashrules.chenzisu.workers.dev/GeneralClashConfig.yml
