[custom]
ruleset=💬 Intelligence,https://clashrules.chenzisu.workers.dev/AI.list
ruleset=💬 Intelligence,https://clashrules.chenzisu.workers.dev/AppleIntelligence.list
ruleset=DIRECT,[]FINAL

; custom_proxy_group=💬 Intelligence`select`[]🇸🇬 SG`[]🇯🇵 JP`[]🇺🇲 US`[]🇨🇳 TW`[]DIRECT
custom_proxy_group=💬 Intelligence`select`[]🇸🇬 SG
custom_proxy_group=🇸🇬 SG`select`^(?!.*(Game|游戏|IPLC)).*(新加坡|坡|狮城|SG|Singapore).*
; custom_proxy_group=🇯🇵 JP`select`^(?!.*(Game|游戏|IPLC)).*(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan).*
; custom_proxy_group=🇺🇲 US`select`^(?!.*(Game|游戏|IPLC)).*(美国|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States).*
; custom_proxy_group=🇨🇳 TW`select`^(?!.*(Game|游戏|IPLC)).*(台|新北|彰化|TW|Taiwan).*

enable_rule_generator=true
overwrite_original_rules=false
clash_rule_base=https://clashrules.chenzisu.workers.dev/GeneralClashConfig.yml
